steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'StackOverflowAnswers'
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment tenant create `
        --name "myDeployment" `
        --location "westeurope" `
        --template-file "bicep/managementGroup/main.bicep"