resources:
  repositories:
    - repository: branchRef
      type: github
      name: wesleycamargo/stackoverflowanswers
      endpoint: Stack Overflow Answers

steps:
  - powershell: |
      $branch = $env:BUILD_SOURCEBRANCH
      
      Write-Host "Git Branch: $branch"
    displayName: 'Set branch name'