parameters:
  - name: "branchName"    
    default: ""

variables:
  - name: "branchName"
    ${{ if eq(parameters.branchName, '') }}:
      value: $(Build.SourceBranch)
    ${{ else }}:
      value: $[parameters.branchName]
    
resources:
  repositories:
    - repository: branchRef
      type: github
      name: wesleycamargo/stackoverflowanswers
      endpoint: Stack Overflow Answers
      ref: $(branchName)
      trigger:
        branches:
          include:
            - main
            - feature/*
      
steps:
  - checkout: branchRef
    
  - powershell: |
      $branch = $env:BUILD_SOURCEBRANCH
      
      Write-Host "Git Branch: $branch"
    displayName: 'Set branch name'