resources:
  repositories:
    - repository: branchRef
      type: github
      name: wesleycamargo/stackoverflowanswers
      endpoint: Stack Overflow Answers
      ref: $(Build.SourceBranch)

trigger:
  branches:
    include:
      - main
      
steps:
  - powershell: |
      $branch = $env:BUILD_SOURCEBRANCH
      
      Write-Host "Git Branch: $branch"
    displayName: 'Set branch name'