parameters:
  - name: "branchName"
    default: $(Build.SourceBranch)

resources:
  repositories:
    - repository: branchRef
      type: github
      name: wesleycamargo/stackoverflowanswers
      endpoint: Stack Overflow Answers
      ref: $(branchName)
      trigger:
        branches:
          include:
            - main
            - feature/*
      
steps:
  - checkout: branchRef
    
  - powershell: |
      $branch = $env:BUILD_SOURCEBRANCH
      
      Write-Host "Git Branch: $branch"
    displayName: 'Set branch name'